In [1]:
import numpy as np


In [2]:
char__arr=np.array(['a','b','c'])
char__arr

array(['a', 'b', 'c'], dtype='<U1')

In [3]:
ch__arr2=np.array(['supervised','unsupervised','sEMi-supervised','reinforcment'])
low__arr=np.char.lower(ch__arr2)
low__arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcment'],
      dtype='<U15')

In [5]:
cleaned__arr=np.char.replace(low__arr,"-","")
cleaned__arr

array(['supervised', 'unsupervised', 'semisupervised', 'reinforcment'],
      dtype='<U14')

In [7]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [8]:
array1.dtype

dtype('int32')

In [15]:
ch__arr2.dtype

dtype('<U15')

In [20]:
array8=np.array([1,2,3,4,5],dtype='float64')
array8

array([1., 2., 3., 4., 5.])

In [21]:
array8.dtype

dtype('float64')

In [24]:
array2conv=array8.astype('f')
array2conv

array([1., 2., 3., 4., 5.], dtype=float32)

In [25]:
char__arr

array(['a', 'b', 'c'], dtype='<U1')

In [26]:
char__conv=char__arr.astype('i')
char__conv

ValueError: invalid literal for int() with base 10: 'a'

In [27]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [29]:
numsone=np.ones((3,2))
numsone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [31]:
ars2=np.zeros(3)
ars2

array([0., 0., 0.])

In [32]:
ars3=np.random.random(3)
ars3

array([0.65451479, 0.40878318, 0.19051177])

In [33]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [34]:
numone=np.ones((3,2))
numone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
numzero=np.zeros((3,2))
numzero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
numzero.astype('i')

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [37]:
dimones=np.ones((4,3,2))

In [38]:
dimones.ndim

3

In [39]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
addition=ar1+ar2
print("addition:\n",addition)


addition:
 [[ 6  8 10]
 [12 14 16]]


In [40]:
subtraction=ar1-ar2
print("subtraction:\n",subtraction)

subtraction:
 [[-4 -4 -4]
 [-4 -4 -4]]


In [41]:
multiplication=ar1*ar2
print("multiplication:\n",multiplication)

multiplication:
 [[ 5 12 21]
 [32 45 60]]


In [42]:
division=ar1/ar2
print("division:\n",division)

division:
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [43]:
power=np.power(ar1,ar2)
print("power:\n",power)

power:
 [[       1       64     2187]
 [   65536  1953125 60466176]]


In [48]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])
result=array2d + array1d
result

array([[11, 22, 25],
       [14, 25, 28]])

In [49]:
range__array=np.arange(0,10,3)
range__array

array([0, 3, 6, 9])

In [50]:
a=np.random.randint(low=1,size=5)
a

array([0, 0, 0, 0, 0])

In [51]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[5, 2, 4],
       [1, 1, 5]])

In [52]:
np.concatenate([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
flatarr=ar1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [54]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [55]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


In [ ]:
import matplotlib.pyplot as plt
from scipy import stats